version: '2.1'
services:

  db:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - mynetwork

  backend:
    container_name: backend
    build: 
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - mynetwork

networks:
  mynetwork: